project_id = "ewfjvgzachtonehujvom"


[functions.multicaixa-express]
verify_jwt = false

[functions.faktura-api]
verify_jwt = false

[functions.subscription-billing]
verify_jwt = false

[functions.saft-submit]
verify_jwt = false
